# Generated by Django 5.2.5 on 2026-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tên bộ dữ liệu')),
                ('category', models.CharField(choices=[('PREPROCESSING', 'Tiền xử lý (Min-Max, Z-score)'), ('ROUGH_SET', 'Tập thô & Rút gọn thuộc tính'), ('KMEANS', 'Phân cụm K-Means'), ('APRIORI', 'Luật kết hợp Apriori'), ('CLASSIFICATION', 'Phân lớp (ID3 & Naive Bayes)')], max_length=50, verbose_name='Phân loại thuật toán')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('data_json', models.JSONField(verbose_name='Nội dung dữ liệu (JSON format)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bộ dữ liệu mẫu',
                'verbose_name_plural': 'Danh sách bộ dữ liệu mẫu',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=100)),
                ('input_parameters', models.JSONField()),
                ('execution_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử thực thi',
                'verbose_name_plural': 'Lịch sử thực thi thuật toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
